### ISSUE TITLE
Automate PyPI release

### ISSUE THREAD

**Issue by jezdez** [mozilla/python_moztelemetry#154]
There is a simple way to allow [release Python packages to PyPI via Travis](https://docs.travis-ci.com/user/deployment/pypi/) on a successful run (or other conditions) when a Git tag is pushed. To simplify the maintenance of the library we should enable this as well. An example config can be found in the [python-dockerflow repo](https://github.com/mozilla-services/python-dockerflow/blob/edd192afdea1d4fafaedbb4672f1773e2737b783/.travis.yml#L15-L24).

**Comment by wlach** [comment]
I just realized we also need to update the docs to reflect this change.

**Comment by maurodoglio** [comment]
This was fixed by #168 and #169
