### ISSUE TITLE
Dataset API returns empty RDD when passing date_submitted tuple (start_date, end_date) but not for a single date string

### ISSUE THREAD

**Issue by jtg567** [mozilla/python_moztelemetry#198]
`pings = Dataset.from_source("telemetry").where(docType= 'main', submissionDate= ("20171012", "20171108")).records(sc, sample= 1)` gives me 
`ValueError: RDD is empty`

vs.

`pings = Dataset.from_source("telemetry").where(docType= 'main', submissionDate= "20171017").records(sc, sample= 1)` which gives me
`fetching 1255763.43384MB in 288192 files...`

[Dataset API docs](http://python-moztelemetry.readthedocs.io/en/stable/api.html#dataset) explicitly state: `submission_date – a submission date or a range of submission dates, e.g: “20150601” or (“20150601”, “20150610”)`

**Comment by jtg567** [comment]
If this isn't something that will be functional within a short duration, could someone from datapipeline share a viable workaround technique for me? I'd be astonished if I was the only one trying to use more than a day worth of data

**Comment by jtg567** [comment]
If this isn't something that will be functional within a short duration, could someone from datapipeline share a viable workaround technique for me? I'd be astonished if I was the only one trying to use more than a day worth of data

**Comment by sunahsuh** [comment]
The line about `submission_date – a submission date or a range of submission dates, e.g: “20150601” or (“20150601”, “20150610”)` is in the docs for the deprecated `get_pings` method -- in the new `Dataset.where()` method that you're using, you need to provide a lambda that filters the parameter

**Comment by harterrt** [comment]
Thanks for reporting this, Josh. I'll let someone else comment on the long-term fix, but here's a work around for now. Try passing a lambda instead of a tuple. For example: 

```python
pings = Dataset.from_source("telemetry").where(docType= 'main', submissionDate=lambda x: x>="20171012" and x<="20171108").records(sc, sample= 1)
```
