### ISSUE TITLE
time rescaling from client to server scale

### ISSUE THREAD

**Issue by gregglind** [mozilla/python_moztelemetry#33]
By necessity, some events are recorded according to the client clock.  

By necessity, some analyses want be done according the the World Clock.  

proposed:

```
def asServerClock(clientTime, ping):
    ...
```

That ties 'creationDate' to `meta/submissionDate`.

**Comment by mreid-moz** [comment]
I don't understand how this would be used - can you give an example?

**Comment by gregglind** [comment]
A number of things are recorded CLIENT RELATIVE (profile creation date,  msg creation date).

Trying to figure out WHEN THESE ARE relative to 'earth time' is a major pita, subject to several assumptions.  (How much delay in AWS recieving, packet midnight rollover, etc).

It also involves *every worksheet dealing with those keys* wasting time reimplementing those same decisions badly.
