### ISSUE TITLE
_read_v4_ranges fails if key is None

### ISSUE THREAD

**Issue by dzeber** [mozilla/python_moztelemetry#39]
With Firefox OS data there are a few filenames for which the return value of `_bucket_v4.get_key` is `None`. This causes `_read_v4_ranges` and hence `get_pings` to fail.

**Comment by dzeber** [comment]
PR #40 fixes the immediate issue by ignoring those filenames, although I'm not sure if this is the best way to handle it.

**Comment by vitillo** [comment]
@mreid-moz Any thoughts on why this happens? I recall you mentioning that some FxOS files get deleted from S3.

**Comment by mreid-moz** [comment]
Files don't get deleted in the new pipeline. When working on the Churn derived stream, I saw some failures to read data from S3, not sure if it's the same problem.

@dzeber is it always the same filenames that return None? Can you send me some examples?

**Comment by dzeber** [comment]
@mreid-moz  I'm sending you some over email. Now that Iook at them, the submission dates are all from August 2015 or earlier, so it might not be a pressing issue.

Code:
```python
import moztelemetry.spark
files = moztelemetry.spark._get_filenames_v4(
    app = "FirefoxOS", source_version = None, doc_type = "OTHER")
keys = [ moztelemetry.spark._bucket_v4.get_key(f) for f in files ]
nonekey_files = [ files[i] for i in range(len(files)) if keys[i] is None ]
```

**Comment by mreid-moz** [comment]
@dzeber The file age was a good clue! It looks like these are files that have auto-expired from the data store after the retention period elapsed.  I bet you're the only person to look that far back in time, which is why nobody else has hit this issue yet :)

@vitillo we should run a cleanup routine to delete filenames from the SimpleDB cache after 180 days.

**Comment by mreid-moz** [comment]
Based on the above (a file that is in the index, but not available in S3), quietly ignoring these files as in PR #40 seems like the right thing to do.
