### ISSUE TITLE
Add _get_source_schema to the API

### ISSUE THREAD

**Issue by dzeber** [mozilla/python_moztelemetry#41]
It would be nice to add access to _get_source_schema in the API. I've found myself looking up the schema before writing the get_pings call to remember what args to use, and this function is a convenient way to access it.

I suppose this will become less of a necessity with practice, although the schema does change sometimes, and it's a pain looking up the s3 path to download it directly.

**Comment by mreid-moz** [comment]
I want to expose all the metadata in a friendly way, just haven't spent much time on API design there.

**Comment by maurodoglio** [comment]
If you use [the new Dataset API](http://python-moztelemetry.readthedocs.io/en/latest/userguide.html#module-moztelemetry.dataset) you can find the list of dimensions on the `schema` attribute. I think that's enough to close this issue.
