### ISSUE TITLE
heka_message_parser.py _lazyjson() breaks dict.__cmp__

### ISSUE THREAD

**Issue by SamPenrose** [mozilla/python_moztelemetry#97]
_wrap() breaks comparison of Python dictionaries to non-dictionary objects. Working with pings loaded from JSON, you need to compare dictionaries a lot:

def descend(d):
    path = ['environment', 'settings', 'defaultSearchEngineData', 'origin']
    while path:
        key = path.pop(0)
        d = d.get(key)
        blowup = d == 'some string'

This fails due to _lazyjson()'s invocation of getattr():

  File "/home/hadoop/anaconda2/lib/python2.7/site-packages/moztelemetry/heka_message_parser.py", line 92, in _wrap
    return method(*args[1:], **kwargs)
TypeError: dict.__cmp__(x,y) requires y to be a 'dict', not a 'str'

Workaround is to test for isinstance(dict, other) before comparing, which may not be obvious to your average bear.

**Comment by vitillo** [comment]
@SamPenrose, can you please file this issue on Bugzilla? It's easier for us to track bugs over there.
